export const STOCKS = [
    { symbol: 'AAPL',  name: 'Apple Inc.',              domain: 'apple.com' },
    { symbol: 'MSFT',  name: 'Microsoft Corporation',   domain: 'microsoft.com' },
    { symbol: 'GOOGL', name: 'Alphabet Inc.',            domain: 'google.com' },
    { symbol: 'AMZN',  name: 'Amazon.com Inc.',          domain: 'amazon.com' },
    { symbol: 'TSLA',  name: 'Tesla Inc.',               domain: 'tesla.com' },
    { symbol: 'META',  name: 'Meta Platforms Inc.',      domain: 'meta.com' },
    { symbol: 'NVDA',  name: 'NVIDIA Corporation',       domain: 'nvidia.com' },
    { symbol: 'NFLX',  name: 'Netflix Inc.',             domain: 'netflix.com' },
    { symbol: 'DIS',   name: 'The Walt Disney Company',  domain: 'disney.com' },
    { symbol: 'BRKB',  name: 'Berkshire Hathaway',       domain: 'berkshirehathaway.com' },
    { symbol: 'JPM',   name: 'JPMorgan Chase & Co.',     domain: 'jpmorganchase.com' },
    { symbol: 'V',     name: 'Visa Inc.',                domain: 'visa.com' },
    { symbol: 'JNJ',   name: 'Johnson & Johnson',        domain: 'jnj.com' },
    { symbol: 'WMT',   name: 'Walmart Inc.',             domain: 'walmart.com' },
    { symbol: 'PG',    name: 'Procter & Gamble Co.',     domain: 'pg.com' },
    { symbol: 'MA',    name: 'Mastercard Inc.',          domain: 'mastercard.com' },
    { symbol: 'HD',    name: 'The Home Depot Inc.',      domain: 'homedepot.com' },
    { symbol: 'BAC',   name: 'Bank of America Corp.',    domain: 'bankofamerica.com' },
  ]